import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { DashboardProvider } from "./context/DashboardContext";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "UAP Routine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <DashboardProvider>
          {children}
          <ToastContainer />
        </DashboardProvider>
      </body>
    </html>
  );
}
